all:	build

build:	get
	go install code.google.com/p/goprotobuf/proto
	go install github.com/kuroneko/configureit

get:
	go get -u code.google.com/p/goprotobuf/proto
	go get -u github.com/kuroneko/configureit

